name: Smoke Tests

on:
  # Run every 2 hours
  schedule:
    - cron: '0 */2 * * *'

  # Allow manual trigger
  workflow_dispatch:

  # Run on push to main (optional, for testing)
  push:
    branches:
      - main

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run smoke tests
        env:
          TEST_BASE_URL: https://imagedb.online
        run: bun test test/smoke.test.ts

      - name: Report failure to GlitchTip
        if: failure()
        run: |
          curl -X POST "http://arkiv.network:8888/api/7/store/" \
            -H "Content-Type: application/json" \
            -H "X-Sentry-Auth: Sentry sentry_key=ed440ed3066b4f6aa8a50d5a5280e4b9, sentry_version=7" \
            -d '{
              "event_id": "'$(uuidgen)'",
              "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%S)'",
              "platform": "other",
              "level": "error",
              "logger": "github-actions",
              "message": "Smoke tests failed on GitHub Actions",
              "environment": "production",
              "tags": {
                "workflow": "smoke-tests",
                "github_run_id": "'${{ github.run_id }}'"
              },
              "extra": {
                "github_repository": "'${{ github.repository }}'",
                "github_ref": "'${{ github.ref }}'",
                "github_sha": "'${{ github.sha }}'",
                "github_actor": "'${{ github.actor }}'",
                "github_run_url": "https://github.com/'${{ github.repository }}'/actions/runs/'${{ github.run_id }}'"
              }
            }'

      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const title = '🚨 Smoke Tests Failed';
            const body = `
            ## Smoke Tests Failed

            The scheduled smoke tests have failed for imagedb.online

            **Details:**
            - Run ID: ${{ github.run_id }}
            - SHA: ${{ github.sha }}
            - Run URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            **Action Required:**
            Please investigate the service health immediately.
            `;

            // Check if similar issue exists
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'smoke-test-failure'
            });

            if (issues.data.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['smoke-test-failure', 'bug', 'production']
              });
            } else {
              // Add comment to existing issue
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issues.data[0].number,
                body: `Another failure detected at ${new Date().toISOString()}\n\nRun URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`
              });
            }
